'use client';

import React from 'react';
import { AlertTriangle, ShieldCheck } from 'lucide-react';
import { cn } from '@/utils/cn';

interface ResearchDisclaimerProps {
  className?: string;
  compact?: boolean;
}

export function ResearchDisclaimer({ className, compact = false }: ResearchDisclaimerProps) {
  if (compact) {
    return (
      <div
        className={cn(
          'flex items-center gap-2 p-3 rounded-lg border border-warning/20 bg-warning/5 text-warning text-[10px] sm:text-xs leading-relaxed',
          className
        )}
      >
        <AlertTriangle className="h-4 w-4 shrink-0 text-warning" />
        <p>
          <strong>Compliance Notice:</strong> This research support tool provides historical-to-forward-looking analyses for decision support only. It does not constitute guaranteed financial advice, investment recommendations, or buy/sell calls.
        </p>
      </div>
    );
  }

  return (
    <div
      className={cn(
        'glass-card rounded-xl border border-warning/20 bg-warning/5 p-4 space-y-3 text-xs sm:text-sm text-foreground/90',
        className
      )}
    >
      <div className="flex items-center gap-2 text-warning font-bold uppercase tracking-wider text-xs">
        <AlertTriangle className="h-4.5 w-4.5 text-warning shrink-0" />
        Regulatory & Explainability Disclaimer
      </div>
      
      <div className="space-y-2 text-muted-foreground leading-relaxed text-xs sm:text-sm">
        <p>
          This module is designed to provide transparent, explainable historical-to-forward-looking analysis of equities. All conclusions, scores, and scenarios generated by this model are derived from public data and transparent scoring rules, and are meant for <strong>informational and decision-support purposes only</strong>.
        </p>
        <p>
          <strong>No Financial Advice:</strong> FolioIntel does not act as a registered investment advisor, broker-dealer, or financial analyst in this capacity. This analysis does not constitute a buy, sell, or hold recommendation. No target prices are provided. Past performance does not guarantee future results.
        </p>
        <p>
          <strong>Scenario Framework:</strong> Forward-looking scenarios (Bull, Base, Bear) represent hypothesis testing based on specified assumptions, not certainties or predictions. Actual outcomes may differ materially from these scenarios depending on macroeconomic cycles, regulatory changes, or company performance.
        </p>
      </div>
      
      <div className="flex items-center gap-1.5 text-success text-xs font-semibold pt-1 border-t border-border/25">
        <ShieldCheck className="h-4 w-4 text-success shrink-0" />
        Traceable Data Policy: Every conclusion in this report is linked to auditable filings and price indices.
      </div>
    </div>
  );
}
